# Generated by Django 5.0.2 on 2024-02-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('tags', models.JSONField()),
                ('stock_status', models.CharField(max_length=50)),
                ('available_stock', models.IntegerField()),
            ],
        ),
    ]
